# Generated by Django 3.1 on 2020-09-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20200911_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='students',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
