# Generated by Django 3.1 on 2020-09-04 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='newprojGroup',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('del_yn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='newproj',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('reg_date', models.DateField()),
                ('end_date', models.DateField()),
                ('del_yn', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second.newprojgroup')),
            ],
        ),
    ]
