# Generated by Django 3.1 on 2020-09-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_auto_20200911_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='second/profiles/', verbose_name="user's profile image"),
        ),
    ]
