# Generated by Django 3.1 on 2020-09-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0004_todo_todogroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Inprogress', 'Inprogress'), ('End', 'End'), ('Pending', 'pending'), ('Inprogress', 'inprogress'), ('End', 'end')], max_length=10),
        ),
    ]
