# Generated by Django 3.1 on 2020-09-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0006_auto_20200907_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Pending', '할일'), ('Inprogress', '진행중'), ('End', '완료')], max_length=10),
        ),
    ]
